__title__ = 'boom_analytics'
__description__ = 'boom analytics package'
__version__ = '0.1.7'
__author__ = 'Lawrence'
__author_email__ = 'lawrence.deng@visionwx.com'
__url__ = 'https://www.visionwx.com'
